export { createDb, type Database } from './client'
export { reconcileEmbeddingDim } from './embeddingSchema'
export { createId, type IdPrefix, idPrefixes } from './ids'
export { runMigrations } from './migrator'
export * as schema from './schema/index'
